# This file was generated by GoReleaser. DO NOT EDIT.
cask "handshake" do
  version "0.18.0"

  on_macos do
    on_intel do
      sha256 "faaf464c87f6142e812377264713120d674f1fee44c2d07e787a8c0be97e07fa"
      url "https://github.com/ThisisBankole/handshake/releases/download/v#{version}/handshake_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "496f44866308e99a3949c32b070e69bfefe6c132c17fb1cb0b56fa17b10c42ef"
      url "https://github.com/ThisisBankole/handshake/releases/download/v#{version}/handshake_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "67f4ffeb6654bf7a3b63f526c08aaf84e44ae0581ff546adf033dd232f99823b"
      url "https://github.com/ThisisBankole/handshake/releases/download/v#{version}/handshake_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "887c6d3eafd8a83ee2b119cc35d1a176ecc82cfdd34c6dd6601ad3f470f5a047"
      url "https://github.com/ThisisBankole/handshake/releases/download/v#{version}/handshake_linux_arm64.tar.gz"
    end
  end

  name "handshake"
  desc "Session portability daemon for AI coding agents"
  homepage "https://github.com/ThisisBankole/handshake"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "handshake"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/handshake"]
    end
    system_command "#{staged_path}/handshake", args: ["setup"]
  end

  # No zap stanza required

  caveats <<~EOS
    Handshake is now installed. The setup wizard will guide you through
    registering with your agents and starting the daemon.

    If the wizard didn't run, start it manually with:
      handshake setup
  EOS
end
