# This file was generated by GoReleaser. DO NOT EDIT.
cask "handshake" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "e8d8124ca4d0aa2c336a5bf50373870356924a434fc63450b793231b060ec23c"
      url "https://github.com/ThisisBankole/handshake/releases/download/v#{version}/handshake_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1f3410e833354fa0fde374199ce95870040aa7d86cb805d352d71495d46cab73"
      url "https://github.com/ThisisBankole/handshake/releases/download/v#{version}/handshake_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dc38bd05a0a57c53939df6b7bb0bcd7b728e5d6488543b039cfa8d3628fada82"
      url "https://github.com/ThisisBankole/handshake/releases/download/v#{version}/handshake_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "97c2d1709365313be81be59c43fce0f0c44646a710478b88ef9e8bffb413dd53"
      url "https://github.com/ThisisBankole/handshake/releases/download/v#{version}/handshake_linux_arm64.tar.gz"
    end
  end

  name "handshake"
  desc "Session portability daemon for AI coding agents"
  homepage "https://github.com/ThisisBankole/handshake"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "handshake"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/handshake"]
    end
    system_command "#{staged_path}/handshake", args: ["setup"]
  end

  # No zap stanza required

  caveats <<~EOS
    Handshake is now installed. The setup wizard will guide you through
    registering with your agents and starting the daemon.

    If the wizard didn't run, start it manually with:
      handshake setup
  EOS
end
