# This file was generated by GoReleaser. DO NOT EDIT.
cask "handshake" do
  version "0.16.0"

  on_macos do
    on_intel do
      sha256 "0522f45c9ec5b03d487838a5322237490c13e0daaae288ae3695918e8fa6432c"
      url "https://github.com/ThisisBankole/handshake/releases/download/v#{version}/handshake_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "927eda1b65dcf2ac9b9a7015f6be521726b5a86f2b5e8aaf36d1f53171790316"
      url "https://github.com/ThisisBankole/handshake/releases/download/v#{version}/handshake_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6882710388fc029380ca411a43011217e14a21fb2fad7947f92e9053f0d4d7da"
      url "https://github.com/ThisisBankole/handshake/releases/download/v#{version}/handshake_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd5852cb0b3db99695b21b1d453c048242f962530cda9e330491147c33149bd7"
      url "https://github.com/ThisisBankole/handshake/releases/download/v#{version}/handshake_linux_arm64.tar.gz"
    end
  end

  name "handshake"
  desc "Session portability daemon for AI coding agents"
  homepage "https://github.com/ThisisBankole/handshake"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "handshake"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/handshake"]
    end
    system_command "#{staged_path}/handshake", args: ["setup"]
  end

  # No zap stanza required

  caveats <<~EOS
    Handshake is now installed. The setup wizard will guide you through
    registering with your agents and starting the daemon.

    If the wizard didn't run, start it manually with:
      handshake setup
  EOS
end
